### ISSUE TITLE
长方形物体间的碰撞检测 code error

### ISSUE THREAD

**Issue by Strong-it** [AlloVince/physics_mathematics_skills_for_game_development#1]
你好，最近在看你翻译的《游戏开发的数学和物理》一书，在书本101页最下面说  当矩形1的下端比矩形2的上端靠下......然而给出的代码确实
if ( ( prcRect1->fBottom > prcRect2->fTop ) &&
             ( prcRect1->fTop    < prcRect2->fBottom ) )
        {
            nResult = true;
        }
}

我认为这里应该是  (prcRect1->fBottom < prcRect2->fTop)  && (prcRect1->fTop > prcRect2->fBottom)
此外我在另外一款开源游戏引擎里面看见判断2个矩形是否相交，给出的代码如下：
public boolean overlaps (Rectangle r) {
        return x < r.x + r.width && x + width > r.x && y < r.y + r.height && y + height > r.y;
    }
是否是我理解错了，如果是作者原著写错了，是否可以在github上先修改相应的代码

**Comment by AlloVince** [comment]
Hi， 因为原书中坐标系是以画面左上角为原点的，所以此处会这样处理。

你的举例坐标系是以画面左下角为原点的，请调整一下思路

**Comment by Strong-it** [comment]
ok, thanks
